### PR TITLE
Add max zoom limit

### LINKED ISSUE #13: Add max zoom limit
As said in the title it would be a nice addition to add a max zoom limit.
Maybe the limit could be when the entire map is the size of the cursor.

Isn't it useless to have so much zoom? 
(It's there somewhere)
image

### PR DESCRIPTION
**Pull request by karolstawowski**
- [x] Created a `ZoomUtils` static class with method to prevent from zooming out more than a 0.1 value with `[-]` button.
- [x] Added max zoom out control to `zoomInOnMouse` method of `Coordinates` class.

Additionally, I thought about setting a `zoom` to 0.1 when next zoom out action would set `zoom` to value smaller than 0.1.

Any feedback desirabled!

Resolves #13

### CODE REVIEW

**Review by tom-mohr — CHANGES_REQUESTED** [review]
Hey ;) thanks for your effort! The app is showing exactly the wanted behavior, that's cool! However, I have some change requests concerning the code:
- Instead of a separate ZoomUtils class, just inline the code like `case "-" -> zoomGoal = Math.max(0.1, zoomGoal / Math.pow(zoomStepFactor, 2));` (but with some MAX_ZOOM variable in Main.java)
- Actually, it should probably be called "MIN_ZOOM", not "MAX_ZOOM", now that I think about it 😄 
- Setting a maximum for the zoom should not be something that the `Coordinates` class is concerned about. Maybe you can rewrite the method `Coordinates.zoomInOnMouse` so that it takes the new zoom value instead of the zoom increase? Then, we can simply pass `Math.max(0.1, newZoom)` as argument when calling the method from the `Main` class.

Hope you can work with my feedback, otherwise just let me know.

**Comment by karolstawowski** [comment]
Hi! I'm happy the outcome of my work met your expectations in terms of functionality. I have made code changes according to your comment!
- [x] Moved [-] button logic to `Main`
- [x] Changed `MAX_ZOOM` to `MIN_ZOOM` (at the beginning I was curious why it was max zoom, but now we're fine 😄)
- [x] Added `newZoom` parameter to `zoomInOnMouse` method of `Coordinates` class. I could not figure out how to get rid of `zoomFactor` as a parameter - it is necessery to shift the camera by dividing original vector - maybe you have some idea on how to improve the code here?

Hope everything will be better this time! 😃

**Comment by tom-mohr** [comment]
Hey, looking very good!👌I just removed the zoomFactor parameter from `Coordinates.zoomInOnMouse()`, you can see my change in #17 . If you don't have any further comments, I will merge #17 tomorrow. Thanks again! 😄

**Comment by karolstawowski** [comment]
Okay, that makes sense now... Thank you for the opportunity to participate in the project! 😀

**Pull request merged**
